name: Release

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TIME_STAMP: ""
      SERVANT_SHA: ""
      CE_SHA: ""
      SERVANT_COLORED_SHA: ""
      CE_COLORED_SHA: ""
    steps:
      - uses: actions/checkout@v4

      - name: Prepare build
        run: |
          timestamp=$(date '+%Y-%m-%d')
          echo "TIME_STAMP=$timestamp" >> $GITHUB_ENV

      - name: Zip directory
        run: |
          if [ ! -d "servant" ]; then
            mkdir servant
          fi
          zip -r servant.zip servant
          sha=`sha256sum servant.zip | awk '{ print $1 }'`
          echo "SERVANT_SHA=$sha" >> $GITHUB_ENV

          if [ ! -d "craft_essence" ]; then
            mkdir craft_essence
          fi
          zip -r craft_essence.zip craft_essence
          sha=`sha256sum craft_essence.zip | awk '{ print $1 }'`
          echo "CE_SHA=$sha" >> $GITHUB_ENV

          if [ ! -d "servant-colored" ]; then
            mkdir servant-colored
          fi
          zip -r servant-colored.zip servant-colored
          sha=`sha256sum servant-colored.zip | awk '{ print $1 }'`
          echo "SERVANT_COLORED_SHA=$sha" >> $GITHUB_ENV

          if [ ! -d "craft_essence-colored" ]; then
            mkdir craft_essence-colored
          fi
          zip -r craft_essence-colored.zip craft_essence-colored
          sha=`sha256sum craft_essence-colored.zip | awk '{ print $1 }'`
          echo "CE_COLORED_SHA=$sha" >> $GITHUB_ENV
    
      - name: Create release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          tag_name: "${{ env.TIME_STAMP }}"
          name: "${{ env.TIME_STAMP }}"
          body: |
            ### Checksums

            | Support | SHA-256 |
            | ------- | ------- |
            | servant.zip | ${{ env.SERVANT_SHA }} |
            | craft_essence.zip | ${{ env.CE_SHA }} |
            | servant-colored.zip | ${{ env.SERVANT_COLORED_SHA }} |
            | craft_essence-colored.zip | ${{ env.CE_COLORED_SHA }} |
          files: |
            servant.zip
            craft_essence.zip
            servant-colored.zip
            craft_essence-colored.zip
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Prune old releases
        uses: dev-drprasad/delete-older-releases@dfbe6be2a006e9475dfcbe5b8d201f1824c2a9fe # v0.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_latest: 5
          delete_tags: true
